name: Run tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1', '1.6']
        architecture: [x64]
        os: [ubuntu-latest]
        python-version: ['3.9']

    steps:
      - name: Setup python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - run: python -m pip install --user matplotlib
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.architecture }}
      - uses: julia-actions/julia-buildpkg@v1
        env:
          PYTHON: python
      - uses: julia-actions/julia-runtest@v1
